applications:
  - ayna-app0
  - ayna-app1
models:
  - publish: 0023
    subscribe: 0022
    application: ayna-app0
  - publish: 0035
    subscribe: 0024
    application: ayna-app0
  - publish: 0015
    subscribe: 0022
    application: ayna-app0
